from flask import Flask, request, jsonify
import os

app = Flask(__name__)

# Load configuration: decide if we're using local models or remote APIs
USE_LOCAL_MODELS = os.getenv("USE_LOCAL_MODELS", "false").lower() == "true"

# Define a dialect map for prompt construction
DIALECT_MAP = {
    "MSA": "باللغة العربية الفصحى",
    "Egyptian": "باللهجة المصرية",
    "Gulf": "باللهجة الخليجية",
    "Levantine": "باللهجة الشامية",
    "Iraqi": "باللهجة العراقية",
    "Tunisian": "باللهجة التونسية",
    "Libyan": "باللهجة الليبية",
    "Sudanese": "باللهجة السودانية",
    "Yemeni": "باللهجة اليمنية",
    "Algerian": "باللهجة الجزائرية",
    "Moroccan": "باللهجة المغربية",
    "Hijazi": "باللهجة الحجازية",
    "Najdi": "باللهجة النجدية",
    "Bahraini": "باللهجة البحرينية",
    "Qatari": "باللهجة القطرية",
    "Emirati": "باللهجة الإماراتية",
    "Kuwaiti": "باللهجة الكويتية",
    "Omani": "باللهجة العمانية",
    "Palestinian": "باللهجة الفلسطينية",
    "Syrian": "باللهجة السورية",
    "Jordanian": "باللهجة الأردنية",
    "Lebanese": "باللهجة اللبنانية"
}

def build_prompt(dialect: str, user_question: str) -> str:
    # Use the selected dialect to build a natural prompt for GPT
    # Add any formatting, examples or context needed for your prompt format
    dialect_phrase = DIALECT_MAP.get(dialect, "باللغة العربية")
    return f"اشرح للمستخدم {dialect_phrase}: {user_question}"

def transcribe_audio_local(audio_path):
    # Use faster-whisper model to transcribe audio locally
    # Developer should:
    # - Load a local Whisper-compatible model (e.g., faster-whisper)
    # - Run transcription on the audio_path
    # - Return the transcribed text
    pass

def transcribe_audio_remote(audio_path):
    # Use OpenAI Whisper API to transcribe audio remotely
    # Developer should:
    # - Upload the file to OpenAI's endpoint
    # - Handle API key and headers securely
    # - Parse the response and extract transcript
    # - Return the transcribed text
    pass

def generate_response_local(prompt):
    # Generate a response using a local LLM (e.g. Ollama running locally)
    # Developer should:
    # - Send the prompt to the local model endpoint (e.g. http://localhost:11434)
    # - Handle JSON formatting
    # - Return the response text from the model
    pass

def generate_response_remote(prompt):
    # Generate a response using OpenAI GPT (e.g. GPT-4)
    # Developer should:
    # - Send the prompt to OpenAI's API with necessary headers
    # - Handle error cases
    # - Return the response text from the model
    pass

@app.route("/ask", methods=["POST"])
def ask():
    # Step 1: Retrieve the input fields from the incoming POST request
    # - Check if there's 'text' input from the user (text field)
    # - Check if there's an uploaded 'audio' file
    # - Also check for the 'dialect' parameter (default to MSA)

    # Step 2: If audio is provided:
    # - Save the uploaded audio file temporarily (e.g., 'temp.wav')
    # - Depending on USE_LOCAL_MODELS flag:
    #     - If True: transcribe the audio using transcribe_audio_local
    #     - Else: transcribe using transcribe_audio_remote
    # - Store the result in 'user_text' and optionally 'transcript'

    # Step 3: If text is provided directly or obtained from transcription:
    # - Build the prompt using build_prompt(dialect, user_text)

    # Step 4: Depending on USE_LOCAL_MODELS:
    #     - If True: generate response using generate_response_local
    #     - Else: generate response using generate_response_remote

    # Step 5: Return a JSON response containing:
    # - "transcript" (only if audio was used)
    # - "response" (the answer generated by the LLM)

    # Step 6: If no input was provided, return an error message with 400 status code
    pass

if __name__ == "__main__":
    app.run(debug=True)
